project_id = "kbjkzugzumejvylwsqml"

[functions.phone-lookup]
verify_jwt = false

[functions.log-visitor]
verify_jwt = false

[functions.get-visitor-logs]
verify_jwt = false

[functions.check-lock-status]
verify_jwt = false

[functions.set-lock-status]
verify_jwt = false
